In [114]:
import plotly.graph_objects as go
import plotly.express as px
import pandas as pd

In [115]:
df = pd.read_csv('data/WALCL.csv')
realGDP_df = pd.read_csv('data/GDPC1.csv')

df['DATE'] = pd.to_datetime(df['DATE'])
realGDP_df['DATE'] = pd.to_datetime(realGDP_df['DATE'])

df.set_index('DATE', inplace=True)
realGDP_df.set_index('DATE', inplace=True)

In [116]:
df = df[df.index.month.isin([1, 4, 7, 10])] # keep only quarterly data

df=df.groupby(df.index.to_period("M")).last() # pick last observation of each quarter

df

           WALCL
DATE
2003-01   712809
2003-04   746294
2003-07   740295
2003-10   747272
2004-01   755279
...          ...
2025-01  6818186
2025-04  6709277
2025-07  6642578
2025-10  6587034
2026-01  6584580

[93 rows x 1 columns]

In [117]:
realGDP_df.index = realGDP_df.index.to_period('M')

realGDP_df

             GDPC1
DATE
1947-01   2182.681
1947-04   2176.892
1947-07   2172.432
1947-10   2206.452
1948-01   2239.682
...            ...
2024-07  23478.570
2024-10  23586.542
2025-01  23548.210
2025-04  23770.976
2025-07  24026.834

[315 rows x 1 columns]

In [118]:
df = df.join(realGDP_df, how="inner")

### Plotting data

In [119]:
df['CBBS % GDP'] = (df['WALCL'] / (df['GDPC1'] * 1000)) * 100

df

           WALCL      GDPC1  CBBS % GDP
DATE
2003-01   712809  14614.141    4.877529
2003-04   746294  14743.567    5.061828
2003-07   740295  14988.782    4.938994
2003-10   747272  15162.760    4.928338
2004-01   755279  15248.680    4.953078
...          ...        ...         ...
2024-07  7178391  23478.570   30.574226
2024-10  7013490  23586.542   29.735135
2025-01  6818186  23548.210   28.954158
2025-04  6709277  23770.976   28.224659
2025-07  6642578  24026.834   27.646497

[91 rows x 3 columns]

In [121]:
fig = px.area(
    df,
    x=df.index.to_timestamp(),
    y="CBBS % GDP",
)

fig.update_layout(
    title=dict(text='Central Bank (Fed) Balance Sheet as % of Real GDP', x=0.5),
    width=1000,
    height=600,
    yaxis=dict(title="%"),
    xaxis=dict(title="Date"),
    hovermode="x unified",
    template="plotly_dark"
)

fig.show()